// WARNING: This File was generated by omegaslc. DO NOT EDIT!

struct OmegaGTEColorVertex{
  float3 pos;
  float4 color;

};

struct ColoredVertexOut{
  float4 pos : POSITION;
  float4 color : COLOR;

};

StructuredBuffer<OmegaGTEColorVertex> vertexBuffer : register(t0);
ColoredVertexOut coloredVertexShader (uint vertexID : SV_VertexID){
  OmegaGTEColorVertex v = vertexBuffer[vertexID];
  ColoredVertexOut o;
  o.pos = float4(v.pos.x, v.pos.y, v.pos.z, 1.0);
  o.color = v.color;
  return o;

};

