// Warning! This file has been generated by omegaslc! DO NOT EDIT!!
#version 450
struct VertexRaster {
  vec4 pos;
  vec4 color;
};

layout(location = 0) out vec4 _outColor;
layout(location = 0) in VertexRaster raster ;
void main(){

  _outColor = raster.color;
}
