// Warning! This file was generated by omegaslc
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct VertexRaster2 {
    simd_float4 pos[[position]];
    simd_float2 coord;
};


fragment simd_float4 myFrag2 (texture2d<float,access::sample> myTexture[[texture(0)]],VertexRaster2 raster [[stage_in]]){
constexpr sampler mySampler = sampler(filter::linear,address::repeat);

    return myTexture.sample(mySampler,raster.coord);
}
