// Warning! This file has been generated by omegaslc! DO NOT EDIT!!
#version 450
layout(location =1) in vec2 VertexRaster2_coord;
layout(location = 0) out vec4 _outColor;
layout(set = 1,binding = 0) uniform texture2D myTexture;
layout(set = 1,binding =1) uniform sampler mySampler;
void main(){

  _outColor = texture(sampler2D(myTexture,mySampler),VertexRaster2_coord);
}
