// Warning! This file has been generated by omegaslc! DO NOT EDIT!!
#version 450
layout(location =1) in vec4 VertexRaster_color;
layout(location = 0) out vec4 _outColor;
void main(){

  _outColor = VertexRaster_color;
}
