// Warning! This file was generated by omegaslc
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct MyVertex2 {
    simd_float4 pos;
    simd_float2 coord;
};


struct VertexRaster2 {
    simd_float4 pos[[position]];
    simd_float2 coord;
};


vertex VertexRaster2 myVertex2 (constant MyVertex2 * v_buffer_2[[buffer(0)]],uint v_id [[vertex_id]]){

    MyVertex2 v = v_buffer_2[v_id];
    VertexRaster2 raster;
    raster.pos = v.pos;
    raster.coord = v.coord;
    return raster;
}
