// Warning! This file was generated by omegaslc
#include <metal_stdlib>
#include <simd/simd.h>

struct VertexRaster {
    simd_float4 pos[[position]];
};


vertex VertexRaster myVertex (uint v_id [[vertex_id]]){
    VertexRaster st;
    return st;
}
