// Warning! This file has been generated by omegaslc! DO NOT EDIT!!
#version 450
struct MyVertex {
  vec4 pos;
  vec4 color;
};

layout(location =1) out vec4 VertexRaster_color;
layout(std430,set = 0,binding = 0) buffer v_buffer_Layout
{
MyVertex v_buffer[];
};
void main(){
  uint vertex_id = gl_VertexIndex;

  MyVertex vert = v_buffer[vertex_id];
  ;
  gl_Position = vert.pos;
  VertexRaster_color = vert.color;
  }
