// Warning! This file has been generated by omegaslc! DO NOT EDIT!!
#version 450
struct MyVertex {
  vec3 pos;
  vec4 color;
};

struct VertexRaster {
  vec4 pos;
  vec4 color;
};

void main(){
  uint vertex_id = gl_VertexIndex;

  MyVertex vert;
  VertexRaster data;
  ;
  gl_Position = data;
}
