// Warning! This file was generated by omegaslc
#include <metal_stdlib>
#include <simd/simd.h>

struct MyVertex {
    simd_float3 pos;
    simd_float4 color;
};


struct VertexRaster {
    simd_float4 pos[[position]];
    simd_float4 color;
};


vertex VertexRaster myVertex (constant MyVertex * v_buffer[[buffer(0)]],uint vertex_id [[vertex_id]]){
    MyVertex vert;
    VertexRaster data;
    ;
    return data;
}
