// Warning! This file was generated by omegaslc. DO NOT EDIT!
#include "omegaGTE/GTEBase.h"
struct MyVertex {
    FVec<3> pos;
    FVec<4> color;
};
#ifdef TARGET_METAL
struct MyVertex_ {
    simd_float3 pos ;
    simd_float4 color ;
};
#endif

